services:
  # Service PHP avec Apache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion_web
    ports:
      - "8095:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=gestion
    restart: always

  # Service MySQL
  db:
    image: mysql:8.0
    container_name: gestion_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=gestion
    restart: always

volumes:
  mysql_data:
